apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: kalaimanims/mavenapp:$IMAGE_NAME
        imagePullPolicy: always
      imagePullSecrets: 
      - name: my-registry-key
      ports:
        containerPort: 8080