apiVersion: v1
kind: deployment
metadata:
  name: $APP_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      name: $APP_NAME
        labels:
          app: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: kalaimanims/mavenapp:$IMAGE_NAME
        imagePullPolicy: always
      imagePullSecrets: 
      ports:
        containerPort: 8080